version: '3'

services:

  db:
    image: mysql:8
    container_name: db_star
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - star

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_star
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MAX_EXECUTION_TIME: 3600
      UPLOAD_LIMIT: 1024M
    networks:
      - star

  www:
    container_name: www_star
    volumes:
      - ./build/vhost.conf:/etc/apache2/sites-enabled/vhosts.conf
      - ../:/var/www
      - ./build/php.ini:/usr/local/etc/php/php.ini
      - ./build/.bashrc:/root/.bashrc
    restart: always
    networks:
      - star

networks:
  star:

volumes:
  db: